[book]
authors = ["Stephen Funk"]
language = "en"
multilingual = false
src = "src"
title = "Learning Rust through Advent of Code"
description = "Learn Rust by tackling the Advent of Code 2022 challenges."
